// COURSES
export const FETCH_FACULTIES = "FECTH_FACULTIES"
export const FETCH_COURSES = "FETCH_COURSES";
export const FETCH_POPULAR_COURSES = "FETCH_COURSES";
// CART
export const FETCH_CART_ITEMS = "FETCH_CART_ITEMS";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const CLEAR_CART = "CLEAR_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
// AUTH
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"
// ERROR
export const GET_ERRORS = "GET_ERRORS"
export const CLEAR_ERRORS = "CLEAR_ERRORS"
//  Loader
export const START_LOADING = 'START_LOADING'
export const STOP_LOADING = 'STOP_LOADING'